### PR TITLE
Ntassone/style 2.0

### PR DESCRIPTION
**Pull request by ntassone**
New base style:

chat

### CODE REVIEW

**Comment by YoDK** [comment]
https://github.com/goinstant/platform/pull/2885
https://github.com/goinstant/components/pull/749

**Comment by YoDK** [comment]
LGTM.

**Comment by YoDK** [comment]
Tests must pass before being merged.

**Comment by nealstewart** [comment]
LGTM. Failures are unrelated to this change. Merging.

**Pull request merged**
